<?php
define('BASE_PATH', '');
define('SITE_ROOT', dirname(__DIR__));
define('NEWS_STORAGE_PATH', SITE_ROOT . '/storage/news');
define('SITE_DB_HOST', '127.0.0.1');
define('SITE_DB_NAME', 'acore_web');
define('SITE_DB_USER', 'root');
define('SITE_DB_PASS', '');
define('SITE_DB_CHARSET', 'utf8mb4');
define('AUTH_DB_HOST', '127.0.0.1');
define('AUTH_DB_NAME', 'acore_auth');
define('AUTH_DB_USER', 'root');
define('AUTH_DB_PASS', '');
define('AUTH_DB_CHARSET', 'utf8mb4');
define('CHARACTERS_DB_HOST', '127.0.0.1');
define('CHARACTERS_DB_NAME', 'acore_characters');
define('CHARACTERS_DB_USER', 'root');
define('CHARACTERS_DB_PASS', '');
define('CHARACTERS_DB_CHARSET', 'utf8mb4');
define('SERVER_NAME', 'test private server');
define('REALM_NAME', 'REALM NAME');
define('REALM_RATE', 'x7');
define('UPTIME_REALM_ID', 1);
define('MAIL_FROM_EMAIL', 'noreply@example.com');
define('MAIL_FROM_NAME', 'WoW Server');
define('MAIL_USE_SMTP', false);
define('SMTP_HOST', '127.0.0.1');
define('SMTP_PORT', 587);
define('SMTP_USER', '');
define('SMTP_PASS', '');
define('SMTP_TLS', true);
define('SITE_PUBLIC_URL', 'http://localhost');
define('SESSION_NAME', 'acore_sid');
define('DEFAULT_LANG', 'en');
define('MMORATING_API_BASE', 'https://mmorating.top/api/v1');
define('ARENA_TYPE_2V2', 0);
define('ARENA_TYPE_3V3', 1);
define('ARENA_TYPE_5V5', 2);
define('CAPTCHA_TYPE', 0);
define('CAPTCHA_GOOGLE_SITE_KEY', '');
define('CAPTCHA_GOOGLE_SECRET', '');
define('CAPTCHA_TURNSTILE_SITE_KEY', '');
define('CAPTCHA_TURNSTILE_SECRET', '');
